"""
Stage 2: Verification Engine
============================

Description:
    This script acts as the "Reviewer" in the two-stage pipeline. It takes a list of
    candidate features (Bounding Boxes) generated by Stage 1, extracts high-resolution
    crops for each, and submits them to a specific "Verifier" prompt (v4.X).

    It can perform multiple iterations (voting) for robust consensus.

    Uses the google-genai SDK with ThinkingConfig support for Gemini 3 models.

Usage:
    python scripts/5_verify_crops.py \\
        --candidates outputs/results/v4.1/candidates.geojson \\
        --output outputs/results/v4.1/verified.geojson \\
        --config prompts/configs/verify_image-only.json \\
        --workers 10

Key Features:
    - Parallel Processing: Uses ThreadPoolExecutor for high throughput.
    - Component-Level Cropping: Extracts exact pixel data from original GeoTIFFs.
    - Visual Chain-of-Thought: Prompts the model to "Scan, Discriminate, Score".
    - Comprehensive Metadata: Full API response tracking via lib_llm_metadata.

Author: Shawn Ross, Adela Sobotkova
Licence: Apache 2.0
"""

import argparse
import concurrent.futures
import io
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import geojson
import rasterio
from geojson import Feature, FeatureCollection
from google import genai
from google.genai import types
from PIL import Image
from rasterio.windows import Window
from shapely.geometry import shape

# Add project root to path so config and scripts modules are importable
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR))

try:
    from config import (
        GOOGLE_API_KEY, TILES_DIR, RASTERS_DIR, CONTEXT_SIZE, EXAMPLES_DIR,
        BASE_DIR,
    )
except ImportError:
    print("Error: config.py not found.")
    sys.exit(1)

from scripts.lib_llm_metadata import (
    LLMMetadataTracker,
    LLMResponseMetadata,
    extract_gemini_metadata,
    create_error_metadata,
    estimate_cost,
    LLMProvider,
)

# Script Version
__version__ = "5.3.0"  # E33: crop from source raster instead of tile

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def _resolve_model_name(client: genai.Client, model_name: str) -> str | None:
    """
    Resolve a model name to its API-available form.

    Configs use marketing names (e.g., 'gemini-3-flash') matching the preregistration,
    but the API may require a '-preview' suffix until Google promotes the model to
    stable. This function checks availability and falls back to the '-preview' variant.

    Args:
        client: Initialised google-genai Client.
        model_name: Model name from config (e.g., 'gemini-3-flash').

    Returns:
        Resolved model name string, or None if the model cannot be found.
    """
    try:
        available = {
            m.name.removeprefix("models/") for m in client.models.list()
        }
    except Exception as e:
        logging.warning("Could not list models: %s — proceeding with '%s' as-is.", e, model_name)
        return model_name

    # Exact match — model name is valid as-is
    if model_name in available:
        return model_name

    # Try with '-preview' suffix
    preview_name = f"{model_name}-preview"
    if preview_name in available:
        logging.info("Model '%s' not found; resolved to '%s'", model_name, preview_name)
        return preview_name

    # Neither found
    logging.error(
        "Model '%s' not found in API (also tried '%s').",
        model_name,
        preview_name,
    )
    flash_pro = sorted(m for m in available if "flash" in m or "pro" in m)
    for m in flash_pro:
        logging.error("  Available: %s", m)
    return None


def load_candidates(candidates_path: Path) -> list[Feature]:
    """Load candidate features from GeoJSON."""
    with open(candidates_path) as f:
        fc = geojson.load(f)
    return fc.get("features", [])


def _tile_id_to_map_name(tile_id: str) -> str:
    """Extract the parent map name from a tile filename.

    Tile filenames follow ``{map_name}_x{origin_x}_y{origin_y}.png``.

    Args:
        tile_id: Tile filename (e.g., "K-35-052-4_32635_x1344_y1344.png").

    Returns:
        Map name (e.g., "K-35-052-4_32635").
    """
    parts = tile_id.rsplit("_x", 1)
    return parts[0]


# Cache resolved raster paths to avoid repeated filesystem lookups
_raster_cache: dict[str, Path | None] = {}


def resolve_raster_for_tile(tile_id: str) -> Path | None:
    """Resolve a tile ID to its parent source GeoTIFF raster.

    Caches lookups so repeated calls for tiles from the same map sheet
    only hit the filesystem once.

    Args:
        tile_id: Tile filename (e.g., "K-35-052-4_32635_x1344_y1344.png").

    Returns:
        Path to the source .tif file, or None if not found.
    """
    map_name = _tile_id_to_map_name(tile_id)
    if map_name not in _raster_cache:
        raster_path = RASTERS_DIR / f"{map_name}.tif"
        if raster_path.exists():
            _raster_cache[map_name] = raster_path
        else:
            # Try case-insensitive glob as fallback
            found = list(RASTERS_DIR.glob(f"{map_name}.*tif*"))
            _raster_cache[map_name] = found[0] if found else None
    return _raster_cache[map_name]


def get_tile_path(tile_id: str) -> Path | None:
    """Resolve tile ID to absolute tile path (fallback for when rasters unavailable)."""
    found = list(TILES_DIR.glob(f"**/{tile_id}"))
    if not found:
        found = list(TILES_DIR.glob(f"**/{tile_id}.png"))

    if found:
        return found[0]
    return None


def crop_candidate(
    raster_path: Path,
    geom: dict[str, Any],
    context_px: int = CONTEXT_SIZE,
) -> Image.Image | None:
    """Crop the source raster around the candidate geometry centroid.

    Uses ``boundless=True`` so crops are always exactly
    ``context_px × context_px`` pixels, even when the centroid is near
    the raster edge. Rasterio pads beyond-edge pixels with fill_value=0.

    This was fixed in E33 — the original implementation could produce
    truncated crops when reading from tile PNGs near tile boundaries.

    Args:
        raster_path: Path to a georeferenced raster (source GeoTIFF or tile PNG).
        geom: GeoJSON geometry dict for the detection.
        context_px: Size of the square crop in pixels (default: CONTEXT_SIZE).

    Returns:
        PIL Image of the crop, or None on failure.
    """
    try:
        with rasterio.open(raster_path) as src:
            bounds = shape(geom).bounds
            cx = (bounds[0] + bounds[2]) / 2
            cy = (bounds[1] + bounds[3]) / 2

            row, col = src.index(cx, cy)
            half_size = context_px // 2
            window = Window(
                col - half_size, row - half_size, context_px, context_px,
            )

            # boundless=True pads beyond raster edges with fill_value=0,
            # guaranteeing exact crop dimensions (E33 fix)
            arr = src.read(window=window, boundless=True, fill_value=0)
            if arr.shape[0] == 0:
                return None

            # Handle RGB, RGBA, and single-band rasters
            if arr.shape[0] >= 3:
                img_data = arr[:3].transpose(1, 2, 0)
            elif arr.shape[0] == 1:
                # Single-band: replicate to 3-band RGB
                import numpy as np
                grey = arr[0]
                img_data = np.stack([grey, grey, grey], axis=-1)
            else:
                img_data = arr.transpose(1, 2, 0)

            return Image.fromarray(img_data)
    except Exception as e:
        logging.error("Error cropping from %s: %s", raster_path, e)
        return None


def construct_verifier_prompt(
    prompt_config: dict[str, Any],
    refs_dir: Path,
) -> tuple[list[types.Part], str]:
    """
    Construct the multimodal reference prompt as types.Part objects.

    Args:
        prompt_config: Verification prompt configuration dictionary.
        refs_dir: Path to the directory containing reference example images.

    Returns:
        Tuple of (reference_parts list, system_instruction text).
    """
    reference_parts: list[types.Part] = []

    # 1. Image Library (Federated) — build Part objects for the new SDK
    for ex in prompt_config.get("examples", []):
        img_path = refs_dir / ex["path"]
        if img_path.exists():
            reference_parts.append(
                types.Part.from_text(text=f"Example: {ex['label']}")
            )
            with open(img_path, "rb") as f:
                image_bytes = f.read()
            suffix = img_path.suffix.lower()
            mime_type = "image/png" if suffix == ".png" else "image/jpeg"
            reference_parts.append(
                types.Part.from_bytes(data=image_bytes, mime_type=mime_type)
            )
        else:
            logging.warning("Missing reference: %s", img_path)

    # 2. Instructions — loaded as system instruction for the new SDK
    instruction_file = prompt_config.get("instruction_file")
    system_instruction = ""
    if instruction_file:
        instr_path = Path(BASE_DIR) / "prompts" / "system-instructions" / instruction_file
        if instr_path.exists():
            with open(instr_path) as f:
                system_instruction = f.read()
        else:
            logging.warning("Instruction file not found: %s. Using default.", instr_path)

    if not system_instruction:
        # Fallback Default (v4.5 style)
        system_instruction = """
        **Task:** Verification.
        **Process:**
        1. **SCAN**: List visual features of the candidate object in the center.
        2. **DISCRIMINATE**: Check for Hard Negatives
           (Is it a Benchmark? Triangulation Point? Text?).
        3. **FACTORS**: List 3 specific factors that REDUCE your confidence.
        4. **SCORE**: Assign a Probability Score (0.0 to 1.0) that this is a BURIAL MOUND.

        **Rubric**:
        * 0.9-1.0: Clear, circular, 3D relief. Verified.
        * 0.6-0.8: Likely mound, fuzziness/intersection present.
        * 0.2-0.5: Ambiguous, random blob, or competing symbol.
        * 0.0-0.1: Rejection (Text, Box, Line).

        Output JSON: {"reasoning": "...", "mound_probability": 0.X}
        """

    return reference_parts, system_instruction


def process_single_candidate(
    args_tuple: tuple,
) -> tuple[Feature | None, list[LLMResponseMetadata]]:
    """
    Helper for parallel processing with comprehensive metadata capture.

    Uses the google-genai SDK for API calls. The client is thread-safe.

    Args:
        args_tuple: Packed tuple of (feat, reference_parts, client, model_name,
            gen_config, iterations, prompt_config, candidate_id).

    Returns:
        Tuple of (processed Feature or None, list of response metadata).
    """
    (
        feat,
        reference_parts,
        client,
        model_name,
        gen_config,
        iterations,
        prompt_config,
        candidate_id,
    ) = args_tuple

    # Configurable thresholds (with backwards-compatible defaults)
    verification_threshold = prompt_config.get("verification_threshold", 0.5)
    majority_vote_fraction = prompt_config.get("majority_vote_fraction", 0.5)

    props = feat.get("properties", {})
    tile_id = props.get("tile_id") or props.get("source_tile")

    metadata_list = []

    if not tile_id:
        return None, metadata_list

    # Resolve to source raster (E33 fix) — fall back to tile PNG if unavailable
    raster_path = resolve_raster_for_tile(tile_id)
    if raster_path:
        crop_source = raster_path
    else:
        crop_source = get_tile_path(tile_id)
        if not crop_source:
            return None, metadata_list

    crop_img = crop_candidate(crop_source, feat["geometry"])
    if not crop_img:
        return None, metadata_list

    # v4.7 Grid Overlay
    if prompt_config.get("grid_overlay", False):
        try:
            from scripts.lib_grid_utils import apply_grid
            crop_img = apply_grid(crop_img)
        except ImportError:
            logging.warning("Outputting grid failed: grid_utils not found.")
        except Exception:
            pass

    try:
        # Convert crop to bytes for the new SDK
        crop_buffer = io.BytesIO()
        crop_img.save(crop_buffer, format="PNG")
        crop_bytes = crop_buffer.getvalue()

        target_label = (
            "**Target Candidate (with 100m Grid):**"
            if prompt_config.get("grid_overlay")
            else "**Target Candidate:**"
        )

        # Build content parts using types.Part objects
        content_parts = list(reference_parts)  # Copy to avoid mutating shared list
        content_parts.append(types.Part.from_text(text=target_label))
        content_parts.append(
            types.Part.from_bytes(data=crop_bytes, mime_type="image/png")
        )

        content = types.Content(parts=content_parts)

        iteration_results = []
        votes = 0
        total_score_sum = 0.0

        for iter_num in range(iterations):
            request_start = datetime.now(timezone.utc)
            iteration_id = f"{candidate_id}_iter{iter_num + 1}"

            try:
                response = client.models.generate_content(
                    model=model_name,
                    contents=content,
                    config=gen_config,
                )

                # Extract comprehensive metadata
                response_metadata = extract_gemini_metadata(
                    response=response,
                    request_start=request_start,
                    model_requested=model_name,
                    item_id=iteration_id,
                    attempt=1,
                )
                metadata_list.append(response_metadata)

                txt = response.text.replace("```json", "").replace("```", "").strip()
                result = json.loads(txt)

                score = result.get("mound_probability", 0.0)
                reason = result.get("reasoning", "")

                is_verified = score >= verification_threshold
                if is_verified:
                    votes += 1
                total_score_sum += score

                iteration_results.append({
                    "score": score,
                    "reason": reason,
                    "verified": is_verified,
                })

            except json.JSONDecodeError as e:
                # Response received but parsing failed
                if "response" in locals():
                    response_metadata = extract_gemini_metadata(
                        response=response,
                        request_start=request_start,
                        model_requested=model_name,
                        item_id=iteration_id,
                        attempt=1,
                    )
                    response_metadata.parse_success = False
                    response_metadata.parse_error = str(e)
                    metadata_list.append(response_metadata)
                continue

            except Exception as e:
                # API error
                error_metadata = create_error_metadata(
                    error=e,
                    request_start=request_start,
                    provider=LLMProvider.GEMINI.value,
                    model_requested=model_name,
                    item_id=iteration_id,
                    attempt=1,
                )
                metadata_list.append(error_metadata)
                continue

        if not iteration_results:
            return None, metadata_list

        # Aggregate results
        feat["properties"]["verifier_results"] = iteration_results
        feat["properties"]["verifier_votes"] = votes
        feat["properties"]["verifier_avg_score"] = total_score_sum / len(iteration_results)
        feat["properties"]["iterations"] = iterations
        feat["properties"]["verification_threshold"] = verification_threshold
        feat["properties"]["majority_vote_fraction"] = majority_vote_fraction
        # Verified if majority vote threshold met
        feat["properties"]["verified"] = votes >= (iterations * majority_vote_fraction)

        return feat, metadata_list

    except Exception as e:
        logging.error("Inference failed for %s: %s", candidate_id, e)
        return None, metadata_list


def run_verification(
    candidates_path: str,
    output_path: str,
    config_path: str,
    workers: int = 5,
    iterations: int = 1,
    model_override: str | None = None,
):
    """
    Main verification loop with parallelism and comprehensive metadata tracking.

    Uses the google-genai SDK with ThinkingConfig support.

    Args:
        candidates_path: Path to input candidates GeoJSON.
        output_path: Path for output verified GeoJSON.
        config_path: Path to verification config JSON.
        workers: Number of parallel workers.
        iterations: Number of voting iterations per candidate.
        model_override: Optional model name to override config.
    """
    with open(config_path) as f:
        prompt_cfg = json.load(f)

    # Configure Gemini client (google-genai SDK)
    if not GOOGLE_API_KEY:
        logging.error("GOOGLE_API_KEY not found.")
        return

    # Use v1alpha API version for ThinkingConfig support
    client = genai.Client(
        api_key=GOOGLE_API_KEY,
        http_options={"api_version": "v1alpha"},
    )

    if model_override:
        model_name = model_override
        logging.info("Model overridden via CLI: %s", model_name)
    else:
        model_name = prompt_cfg.get("model", "gemini-3-flash")

    # Resolve model name — configs use marketing names (e.g., 'gemini-3-flash')
    # but the API may require the '-preview' suffix
    model_name = _resolve_model_name(client, model_name)
    if model_name is None:
        return

    candidates = load_candidates(Path(candidates_path))
    logging.info(
        "Loaded %d candidates. Concurrent Workers: %d. Iterations per candidate: %d",
        len(candidates),
        workers,
        iterations,
    )

    reference_parts, system_instruction = construct_verifier_prompt(
        prompt_cfg, EXAMPLES_DIR,
    )

    # Build generation config with ThinkingConfig support
    thinking_config = None
    if "thinking_level" in prompt_cfg:
        thinking_config = types.ThinkingConfig(
            thinking_level=prompt_cfg["thinking_level"],
        )
        logging.info("Thinking level: %s", prompt_cfg["thinking_level"])

    gen_config = types.GenerateContentConfig(
        temperature=prompt_cfg.get("temperature", 0.1),
        max_output_tokens=prompt_cfg.get("max_output_tokens", 8192),
        response_mime_type="application/json",
        thinking_config=thinking_config,
        system_instruction=system_instruction,
        safety_settings=[
            types.SafetySetting(
                category="HARM_CATEGORY_HARASSMENT",
                threshold="OFF",
            ),
            types.SafetySetting(
                category="HARM_CATEGORY_HATE_SPEECH",
                threshold="OFF",
            ),
            types.SafetySetting(
                category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                threshold="OFF",
            ),
            types.SafetySetting(
                category="HARM_CATEGORY_DANGEROUS_CONTENT",
                threshold="OFF",
            ),
        ],
    )

    # Initialise metadata tracker
    metadata_tracker = LLMMetadataTracker(
        config=prompt_cfg,
        system_instruction=system_instruction,
        script_name="5_verify_crops.py",
        script_version=__version__,
    )

    verified_features = []

    # Prepare args with unique candidate IDs
    process_args = [
        (
            c,
            reference_parts,
            client,
            model_name,
            gen_config,
            iterations,
            prompt_cfg,
            f"cand_{i:04d}",
        )
        for i, c in enumerate(candidates)
    ]

    completed = 0
    total = len(candidates)
    verified_count = 0
    rejected_count = 0

    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
        future_to_cand = {
            executor.submit(process_single_candidate, arg): arg
            for arg in process_args
        }

        for future in concurrent.futures.as_completed(future_to_cand):
            completed += 1
            if completed % 5 == 0:
                logging.info("Progress: %d/%d", completed, total)

            try:
                result_feat, response_metadata_list = future.result()

                # Log all response metadata
                for meta in response_metadata_list:
                    metadata_tracker.log_response(meta.item_id or "unknown", meta)

                if result_feat:
                    verified_features.append(result_feat)
                    metadata_tracker.log_success(f"cand_{completed:04d}")
                    if result_feat["properties"].get("verified"):
                        verified_count += 1
                    else:
                        rejected_count += 1
                else:
                    metadata_tracker.log_failure(f"cand_{completed:04d}", "No valid result")

            except Exception as e:
                logging.error("Worker exception: %s", e)
                metadata_tracker.log_failure(f"cand_{completed:04d}", str(e))

    # Save verified features
    logging.info("Saving %d verified results to %s", len(verified_features), output_path)
    fc = FeatureCollection(verified_features)
    with open(output_path, "w") as f:
        geojson.dump(fc, f)

    # Update results summary
    metadata_tracker.update_results_summary({
        "candidates_processed": len(candidates),
        "features_with_results": len(verified_features),
        "verified_true": verified_count,
        "verified_false": rejected_count,
        "iterations_per_candidate": iterations,
    })

    # Estimate costs
    cost_estimate = estimate_cost(
        usage=metadata_tracker.usage,
        provider=LLMProvider.GEMINI.value,
        model=model_name,
    )

    # Finalise and save metadata
    meta = metadata_tracker.finalise(include_per_item=True)
    meta["cost_estimate"] = cost_estimate

    meta_file = Path(output_path).with_suffix(".meta.json")
    with open(meta_file, "w") as f:
        json.dump(meta, f, indent=2)

    # Print summary
    logging.info("Metadata saved to %s", meta_file)
    logging.info("Candidates processed: %d", len(candidates))
    logging.info("Verified: %d, Rejected: %d", verified_count, rejected_count)
    logging.info("Tokens used: %s", f"{meta['usage_stats']['total_tokens']:,}")
    logging.info("Estimated cost: $%.4f", cost_estimate["total_cost_usd"])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--workers", type=int, default=5)
    parser.add_argument("--iterations", type=int, default=1)
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Override the model in the config (e.g. gemini-3-flash)",
    )
    args = parser.parse_args()

    run_verification(
        args.candidates,
        args.output,
        args.config,
        args.workers,
        args.iterations,
        model_override=args.model,
    )
