
import geopandas as gpd
import pandas as pd
from pathlib import Path
import json
import numpy as np

# Import metrics logic (copied simplified version to be standalone/reliable)
def calculate_metrics(pred_gdf, ref_gdf, bounds_gdf):
    if pred_gdf.empty:
        return 0, 0, 0
    
    # Spatial Join with Tolerance
    # Buffer refs by 20m
    ref_buf = ref_gdf.copy()
    ref_buf['geometry'] = ref_buf.geometry.buffer(20)
    
    # Check hits
    # Preds that hit a Ref
    hits = gpd.sjoin(pred_gdf, ref_buf, how='inner', predicate='intersects')
    tp = len(hits.index.unique())
    fp = len(pred_gdf) - tp
    
    # Check misses (Refs in bounds not hit)
    # Filter refs to bounds
    search_area = bounds_gdf.geometry.union_all()
    refs_in_scope = ref_gdf[ref_gdf.intersects(search_area)]
    
    # We need to use the HITs to determine how many refs were found.
    # Group hits by index_right (ref index)
    found_refs = len(hits['index_right'].unique())
    fn = len(refs_in_scope) - found_refs
    
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = found_refs / (found_refs + fn) if (found_refs + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    
    return precision, recall, f1

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--pattern", default="run_*")
    parser.add_argument("--thresholds", nargs="+", type=int, default=[1, 2, 3, 4, 5])
    args = parser.parse_args()

    base_dir = Path(args.input)
    # Glob for files matching pattern; handle extensionless
    run_files = list(base_dir.glob(args.pattern))
    # Filter out .meta.json
    run_files = [f for f in run_files if not f.name.endswith(".json")]
    
    print(f"Found {len(run_files)} run files in {base_dir}")
    
    if not run_files:
        print("No files found.")
        return

    # Load All
    gdfs = []
    for f in run_files:
        try:
            # Try loading as geojson
            # Note: outputs might not have .geojson extension but are geojson
            with open(f, 'r') as fh:
                data = json.load(fh)
            
            # create gdf
            if "features" in data and data["features"]:
                gdf = gpd.GeoDataFrame.from_features(data["features"])
                gdf['run_id'] = f.name
                # Ensure CRS
                if "crs" in data:
                    gdf.set_crs(data["crs"]["properties"]["name"], allow_override=True, inplace=True)
                gdfs.append(gdf)
            else:
                pass # Empty
        except Exception as e:
            print(f"Skipping error file {f.name}: {e}")
            
    if not gdfs:
        print("No valid data loaded.")
        return
        
    all_preds = pd.concat(gdfs, ignore_index=True)
    print(f"Total detections across {len(gdfs)} valid runs: {len(all_preds)}")
    
    # ... (Clustering Logic - Keep same)
    all_preds['geom_wkt'] = all_preds.geometry.to_wkt()
    
    grouped = all_preds.groupby('geom_wkt').agg({
        'run_id': 'count', 
        'geometry': 'first',
        # 'verifier_avg_score': 'mean' # Verify score might not exist in job B output
    }).rename(columns={'run_id': 'votes'})
    
    # Check CRs
    crs = gdfs[0].crs
    
    unique_candidates = gpd.GeoDataFrame(grouped, geometry='geometry', crs=crs)
    print(f"Unique candidates identified: {len(unique_candidates)}")
    print("Vote distribution:")
    print(unique_candidates['votes'].value_counts().sort_index())
    
    # Load Refs and Bounds
    # Try to find them dynamically or hardcode to known locations
    ref_files = list(Path("inputs/references").glob("*.geojson"))
    gt_file = next((f for f in ref_files if "gt" in f.name), None)
    
    # Bounds - assume standard manifest was used, so use the bounds generated by any run
    # Or try to find a bounds sidecar
    bounds_path = next(base_dir.glob("*_bounds.geojson"), Path("outputs/results/v4.2_temp_0_7_train/run_01_bounds.geojson"))
    
    if not gt_file or not bounds_path.exists():
        print(f"Missing GT ({gt_file}) or Bounds ({bounds_path}).")
        # Proceed with partial output? No, validaton needs recall.
        # Hardcode fallback for GT
        gt_file = Path("inputs/vectors/mounds-reference.geojson")
        
    print(f"Using GT: {gt_file}")
    
    gdf_ref = gpd.read_file(gt_file)
    if gdf_ref.crs != unique_candidates.crs:
        gdf_ref = gdf_ref.to_crs(unique_candidates.crs)
        
    gdf_bounds = gpd.read_file(bounds_path)
    if gdf_bounds.crs != unique_candidates.crs:
        gdf_bounds = gdf_bounds.to_crs(unique_candidates.crs)

    print("\n--- Consensus Results ---")
    print(f"{'N':<5} {'Count':<10} {'Precision':<10} {'Recall':<10} {'F1':<10}")
    
    results = []
    
    for n in args.thresholds:
        subset = unique_candidates[unique_candidates['votes'] >= n]
        if subset.empty:
            p, r, f1 = 0, 0, 0
            count = 0
        else:
            p, r, f1 = calculate_metrics(subset, gdf_ref, gdf_bounds)
            count = len(subset)
            
        print(f"{n:<5} {count:<10} {p:<10.4f} {r:<10.4f} {f1:<10.4f}")
        results.append({"n": n, "f1": f1})

if __name__ == "__main__":
    main()
