#!/usr/bin/env python3
"""
Add the seven Track-2 ``-canonical-gt`` condition specs to ``run-conditions.json``
(Session 105, O1) — idempotently.

(O1 specified an "@canonical-gt" suffix; the conditions-manifest schema's
``condition_id`` pattern ``^[a-z0-9-]+::[a-z0-9._-]+$`` forbids ``@``, so the
schema-valid ``-canonical-gt`` is used instead — same intent, greppable.)
===========================================================================

Registers, against the four 55-map run families, the deployment-oracle cells
re-scored against the **canonical adjudicated extended GT** (the paper
reference). Each spec points ``eval_path`` at the generator-compatible
``evaluation.json`` produced by ``adapt_track2_evals_for_manifest.py``; the
conditions-manifest is then regenerated by ``generate_post_run_report.py --all``.

Seven cells (label per run; ``condition_id`` = ``<run>::<label>``):

* ``55maps-text-high-generalisation``    → ``verified-k4-canonical-gt`` (carry-forward),
  ``verified-k3-canonical-gt``
* ``55maps-text-high-t0-3-generalisation`` → ``verified-k4-canonical-gt``,
  ``verified-k3-canonical-gt`` (the deployment ORACLE)
* ``55maps-text-min-generalisation``     → ``verified-k4-canonical-gt``,
  ``verified-k3-canonical-gt``
* ``55maps-image-generalisation``        → ``verified-k3-canonical-gt`` (carried 3-of-5)

Text k3 cells use the Session-104 vote=3 shell (vote 3, prob ≥ 0.15); k4 and the
image k3 reuse the carried verified detections (prob null). Verifier config is
mirrored from each run's existing ``verified`` condition (same verifier family;
the operating point differs in vote/prob, recorded explicitly).

Idempotent: re-running skips labels already present. Also appends a canonical-
track cross-reference to each run's ``_note`` (T1c) once.

Usage::  python scripts/add_canonical_gt_conditions.py

Author: Shawn Ross, Claude Code
Licence: Apache 2.0
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RUN_CONDITIONS = REPO / "results/run-conditions.json"
EVAL_BASE = "results/55maps-extended-gt-2026-06-07"
K3DIR = "results/deployment-oracle-2026-06-06/k3-scoring"

CROSSREF_NOTE = (
    " | Session 105: also carries the canonical extended-GT (Track-2) conditions "
    "'verified-k4-canonical-gt'/'verified-k3-canonical-gt' (paper reference; "
    "see results/55maps-extended-gt-2026-06-07/ and "
    "results/deployment-oracle-2026-06-06/deployment-oracle-findings.md). The "
    "existing 'verified' condition is the historical reviewed-student-GT (Track-1) "
    "score."
)

# run_id → list of (label, cell, vote, prob, detections)
SPECS: dict[str, list[tuple[str, str, int, float | None, str]]] = {
    "55maps-text-high-generalisation": [
        ("verified-k4-canonical-gt", "TH7-k4", 4, None,
         "outputs/55maps-text-high-generalisation/verified/verified_detections.geojson"),
        ("verified-k3-canonical-gt", "TH7-k3", 3, 0.15,
         f"{K3DIR}/55maps-text-high-generalisation/k3_verified.geojson"),
    ],
    "55maps-text-high-t0-3-generalisation": [
        ("verified-k4-canonical-gt", "T03-k4", 4, None,
         "outputs/55maps-text-high-t0.3-generalisation/verified/verified_detections.geojson"),
        ("verified-k3-canonical-gt", "T03-k3", 3, 0.15,
         f"{K3DIR}/55maps-text-high-t0.3-generalisation/k3_verified.geojson"),
    ],
    "55maps-text-min-generalisation": [
        ("verified-k4-canonical-gt", "TM-k4", 4, None,
         "outputs/55maps-text-min-generalisation/verified/verified_detections.geojson"),
        ("verified-k3-canonical-gt", "TM-k3", 3, 0.15,
         f"{K3DIR}/55maps-text-min-generalisation/k3_verified.geojson"),
    ],
    "55maps-image-generalisation": [
        ("verified-k3-canonical-gt", "IM-k3", 3, None,
         "outputs/55maps-image-generalisation/verified/verified_detections.geojson"),
    ],
}

# Per-cell human note (documents role; not copied into the generated manifest).
ROLE = {
    "TH7-k4": "carry-forward (text HIGH T0.7, vote 4-of-5) re-scored vs canonical extended GT",
    "TH7-k3": "text HIGH T0.7, vote 3-of-5 (Session-104 vote=3 shell, prob>=0.15)",
    "T03-k4": "text HIGH T0.3, vote 4-of-5, vs canonical extended GT",
    "T03-k3": "DEPLOYMENT ORACLE — text HIGH T0.3, vote 3-of-5 (vote=3 shell, prob>=0.15)",
    "TM-k4": "text MINIMAL, vote 4-of-5, vs canonical extended GT",
    "TM-k3": "text MINIMAL, vote 3-of-5 (vote=3 shell, prob>=0.15)",
    "IM-k3": "image, carried vote 3-of-5, vs canonical extended GT",
}


def main() -> None:
    """Add the specs + cross-reference notes, idempotently."""
    doc = json.loads(RUN_CONDITIONS.read_text())
    dec = doc["decomposition"]
    added = 0
    for run_id, specs in SPECS.items():
        entry = dec[run_id]
        verifier_config = entry["conditions"][0]["verifier_config"]
        proposer_pool = entry["conditions"][0]["proposer_pool"]
        existing = {c["label"] for c in entry["conditions"]}
        for label, cell, vote, prob, det in specs:
            if label in existing:
                print(f"  skip (exists): {run_id}::{label}")
                continue
            entry["conditions"].append({
                "label": label,
                "architecture": "proposer-verifier",
                "aggregation": "verified",
                "proposer_pool": proposer_pool,
                "n_passes": 5,
                "vote_threshold": vote,
                "prob_threshold": prob,
                "verifier_config": verifier_config,
                "eval_path": f"{EVAL_BASE}/{cell}/evaluation.json",
                "detections": det,
                "_note": ROLE[cell],
            })
            added += 1
            print(f"  added: {run_id}::{label}  (cell {cell})")
        # T1c: append the canonical-track cross-reference to the run _note (once).
        if "canonical extended-GT (Track-2)" not in entry.get("_note", ""):
            entry["_note"] = entry.get("_note", "") + CROSSREF_NOTE

    RUN_CONDITIONS.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"\n{added} condition(s) added; run-conditions.json rewritten.")


if __name__ == "__main__":
    main()
