#!/usr/bin/env python3
"""
BCa migration queue builder.

Enumerates every ``evaluation.json`` under ``results/`` that was generated
by ``scripts/evaluate_detections.py`` AND whose recorded bootstrap method
is anything other than ``"BCa"``, then emits a queue CSV in the schema
that ``scripts/run_bootstrap_10k.py`` consumes. The runner re-runs each
cell with ``--bootstrap 10000``; because ``lib_advanced_metrics.py``
unconditionally uses BCa as of commit ``2026999a`` (2026-04-29), the
re-run upgrades the cell from schema 1.0 (percentile) to schema 1.1
(BCa) and populates the new ``point`` fields plus the Mitigation 3
``coverage_status`` block.

Migration scope (Session 81 close-out, planning/paper-writeup-continuity.md item #12):

* ALL committed evaluation cells generated by ``evaluate_detections.py``
* Excludes verifier-t-pilot/* (different pipeline)
* Excludes any cell already at ``_metadata.bootstrap.method == "BCa"``

The queue is built from each cell's own ``_metadata`` block. That block is
NOT uniformly authoritative, and two of its fields lie for batch-scored
cells — the Session 137 audit (finding F9, defects D33/D37) found the
queue unexecutable as a result, on all 22 rows:

* ``cli_args.buffers`` records the unoverridden argparse default
  ``[20]`` whenever the buffers came from a ``--batch`` YAML, so the
  queue asked for a one-buffer re-score of cells that actually ran the
  14-buffer standard. The buffers that RAN are recoverable from the
  cell's own ``summary.buffers``, and that is what is used here.
* ``cli_args.detections`` / ``detections_dir`` are both null for batch
  cells (the batch-level invocation is what got serialised), leaving the
  detection-source columns empty. The per-cell input survives in
  ``_metadata.input_files.detections``; the same D22 fallback chain that
  ``scripts/era1_leaderboard_tiering.py`` ``load_cells`` applies is
  mirrored below. It is mirrored rather than shared because the two
  scripts have no common import today; see :func:`recover_recipe`.

A cell whose detection input is recovered that way is rewritten as a
PER-CELL invocation (``--batch`` dropped, ``--output-dir`` pointed at the
cell's own directory, ``--label`` taken from ``summary.label``) — a row
carrying both ``batch`` and ``detections_dir`` would be ambiguous, and
the batch-level ``output_dir`` would write one directory too high.

The queue has never been executed (verified by the audit: the target
tree's ``git diff`` is empty), so no committed artefact depends on the
pre-fix rows.

The migration is deterministic: F1, P, R, MCC, sensitivity, and
specificity ``point`` estimates do not depend on the bootstrap
distribution and so are identical pre- vs post-migration to within
float-precision rounding. Only CI bounds shift (typically <0.005 absolute
on F1) and new schema fields appear.

Output:
    /tmp/bca-migration-queue.csv      (canonical name per task brief)
    /tmp/bootstrap-10k-jobs.csv       (runner's hard-coded path)

Usage:
    # Default: build queue, write both CSVs:
    python3 scripts/build_bca_migration_queue.py

    # Validate paths before writing:
    python3 scripts/build_bca_migration_queue.py --validate-paths

    # Override output path:
    python3 scripts/build_bca_migration_queue.py --output /tmp/foo.csv

Author: Claude Code (Opus 4.7, 1M context) for Shawn Ross's BCa migration
sweep, 2026-04-29.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.lib_detection_paths import resolve_pool_passes  # noqa: E402

DEFAULT_OUTPUT = Path("/tmp/bca-migration-queue.csv")
RUNNER_QUEUE = Path("/tmp/bootstrap-10k-jobs.csv")
RESULTS_DIR = REPO_ROOT / "results"


def enumerate_eval_cells() -> list[Path]:
    """Find every ``evaluation.json`` file under ``results/``.

    Returns:
        Sorted list of absolute paths to ``evaluation.json`` files.
    """
    return sorted(RESULTS_DIR.rglob("evaluation.json"))


def needs_migration(eval_path: Path) -> tuple[bool, str]:
    """Decide whether an evaluation cell should be re-run under BCa.

    Args:
        eval_path: Absolute path to the cell's ``evaluation.json``.

    Returns:
        Tuple ``(in_scope, reason)``. ``in_scope`` is ``True`` if the
        cell needs migration; ``reason`` is a short string explaining
        the verdict (used for skip-counter telemetry).
    """
    try:
        with open(eval_path) as f:
            d = json.load(f)
    except Exception as e:
        return False, f"load_failed:{e!s}"
    md = d.get("_metadata") or {}
    if not md:
        return False, "no_metadata"
    script = md.get("script_path") or md.get("script") or ""
    method = (md.get("bootstrap") or {}).get("method")
    if not script:
        # 40 committed cells record no generating script at all (24 under
        # results/verifier-t-pilot/, 16 adapter-written 55-map cells).
        # Reporting them as "not_evaluate_detections" asserted knowledge
        # the artefact does not carry, and hid two facts a reader needs:
        # they are ALSO recipe-less (no cli_args, no input_files — the
        # D33 reproducibility gap), and they are NOT known to be BCa, so
        # a future migration still owes them an answer. Both go in the
        # label (defect D33, audit finding F9).
        has_recipe = bool(md.get("cli_args") or md.get("input_files"))
        return False, (
            f"script_not_recorded(bootstrap_method={method or 'unrecorded'}"
            f", recipe={'yes' if has_recipe else 'none'})"
        )
    if "evaluate_detections" not in script:
        return False, "not_evaluate_detections"
    if method == "BCa":
        return False, "already_bca"
    return True, "needs_migration"


def recover_recipe(document: dict[str, Any]) -> dict[str, Any]:
    """Return a cell's effective ``cli_args`` with the D22 fallback applied.

    Mirrors ``scripts/era1_leaderboard_tiering.py`` ``load_cells``: an
    evaluation's recorded ``cli_args`` is incomplete for two families,
    and ``_metadata.input_files`` carries the missing pieces.

    * ADAPTER-written cells have no ``cli_args`` at all; ``input_files``
      is the only recipe they have.
    * BATCH-scored cells serialise the batch-level invocation, so
      ``detections`` and ``detections_dir`` are both null while the
      per-cell input sits in ``input_files.detections``.

    This is a mirror, not a shared helper: ``era1_leaderboard_tiering``
    and this builder have no common import today, and introducing one
    would mean editing a third script. If a future change gives them a
    shared module, both copies should move into it — the defect register
    tracks this under D22 / D33.

    The mirror is slightly hardened: it replaces falsy values rather than
    only absent keys, so a recorded ``"bounds": null`` is filled in too.

    Args:
        document: The parsed ``evaluation.json``.

    Returns:
        A new dict — the recorded ``cli_args`` plus whatever
        ``input_files`` could supply. Never mutates the input.
    """
    metadata = document.get("_metadata") or {}
    cli = dict(metadata.get("cli_args") or {})
    input_files = metadata.get("input_files") or {}

    for key in ("bounds", "ground_truth"):
        if not cli.get(key) and input_files.get(key):
            cli[key] = input_files[key]

    if not (cli.get("detections") or cli.get("detections_dir")):
        fallback = input_files.get("detections")
        if isinstance(fallback, str) and fallback:
            cli["detections_dir"] = fallback
        elif isinstance(fallback, list) and fallback:
            cli["detections"] = fallback
    return cli


def buffers_that_ran(
    document: dict[str, Any], cli_args: dict[str, Any],
) -> list[int]:
    """Return the buffer list the evaluation ACTUALLY scored.

    ``cli_args.buffers`` is the argparse namespace as parsed, so for a
    ``--batch`` invocation it holds the unoverridden default ``[20]``
    while the batch YAML supplied the real grain — a default published
    as a measurement, the D17 class on a new field (audit finding F9).
    The cell's own ``summary.buffers`` is a measurement: one row per
    buffer that was scored.

    Args:
        document: The parsed ``evaluation.json``.
        cli_args: The recovered recipe (see :func:`recover_recipe`),
            used only as a fallback when no summary rows exist.

    Returns:
        Buffer sizes in metres, in recorded order, duplicates removed.
    """
    rows = (document.get("summary") or {}).get("buffers")
    measured: list[int] = []
    if isinstance(rows, list):
        for row in rows:
            if not isinstance(row, dict):
                continue
            value = row.get("buffer_metres")
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                continue
            measured.append(int(value))
    if not measured:
        declared = cli_args.get("buffers") or []
        measured = [
            int(b) for b in declared
            if not isinstance(b, bool) and isinstance(b, (int, float))
        ]
    return list(dict.fromkeys(measured))


def make_row(eval_path: Path, document: dict[str, Any]) -> dict[str, str]:
    """Construct a queue-CSV row from a cell's own evaluation document.

    The whole document is taken (not just ``cli_args``) because two of
    the row's columns are only recoverable from elsewhere in it: the
    buffer grain from ``summary.buffers`` and, for batch-scored cells,
    the detection input from ``_metadata.input_files`` and the label
    from ``summary.label``. See the module docstring for why the
    recorded ``cli_args`` cannot be trusted on its own.

    Args:
        eval_path: Absolute path to the cell's ``evaluation.json``.
        document: The parsed contents of that file.

    Returns:
        Dict in the schema expected by ``run_bootstrap_10k.py``.
    """
    cli_args = recover_recipe(document)
    summary = document.get("summary") or {}
    rel_eval = str(eval_path.relative_to(REPO_ROOT))
    cell_dir = str(eval_path.parent.relative_to(REPO_ROOT))
    output_dir = cli_args.get("output_dir") or cell_dir

    # Detection source: list-of-files OR detections_dir OR batch.
    det_list = cli_args.get("detections") or []
    if isinstance(det_list, str):
        det_list = [det_list]
    detections_field = "|".join(det_list) if det_list else ""
    det_dir = cli_args.get("detections_dir") or ""
    batch = cli_args.get("batch") or ""
    glob = cli_args.get("glob") or ""

    bounds = cli_args.get("bounds") or ""
    gt = cli_args.get("ground_truth") or ""
    buffers = " ".join(str(b) for b in buffers_that_ran(document, cli_args))
    seed = str(cli_args.get("seed") or 42)
    label = cli_args.get("label") or ""
    mcc = "1" if cli_args.get("mcc") else "0"

    # A batch cell whose per-cell detection input was recovered becomes a
    # PER-CELL invocation. Leaving ``batch`` set alongside the recovered
    # source would hand the runner two contradictory inputs, and the
    # batch-level ``output_dir`` is the PARENT of the cell directory
    # (batch mode appends ``slugify(label)``), so re-running with it
    # would write one level too high. ``summary.label`` is the label the
    # batch YAML supplied, and its slug is the cell directory name.
    if batch and (detections_field or det_dir):
        batch = ""
        output_dir = cell_dir
        label = label or summary.get("label") or ""
        # ``cli_args.glob`` is an argparse default here too — the same
        # defect as ``buffers``. Four of these cells recorded the
        # convention-A (underscore) pattern while their batch YAML
        # supplied the convention-B (hyphen) one, so the recorded
        # pattern resolves ZERO files against their pools. Blanking the
        # column hands the decision to ``evaluate_detections.py``'s
        # canonical resolver, which matches both per-pass filename
        # conventions (defect D6, lib_detection_paths.resolve_pool_passes)
        # instead of the batch-written shape alone.
        glob = ""

    return {
        "status": "queued",
        "eval_path": rel_eval,
        "output_dir": output_dir,
        "detections": detections_field,
        "detections_dir": det_dir,
        "glob": glob,
        "batch": batch,
        "bounds": bounds,
        "ground_truth": gt,
        "buffers": buffers,
        "bootstrap": "10000",  # traceability only; runner forces 10000
        "seed": seed,
        "label": label,
        "mcc": mcc,
    }


def validate_row(row: dict[str, str]) -> list[str]:
    """Verify that every path referenced by a queue row exists on disk.

    Args:
        row: The queue row dict from :func:`make_row`.

    Returns:
        List of error strings (empty if all paths are valid).
    """
    problems: list[str] = []
    for key in ("bounds", "ground_truth"):
        p = row[key]
        if not p:
            problems.append(f"{key} is empty")
        elif not (REPO_ROOT / p).exists():
            problems.append(f"{key}={p} not found")
    if row["detections"]:
        for d in row["detections"].split("|"):
            if not (REPO_ROOT / d).exists():
                problems.append(f"detections={d} not found")
    elif row["detections_dir"]:
        det_dir_abs = REPO_ROOT / row["detections_dir"]
        if not det_dir_abs.exists():
            problems.append(f"detections_dir={row['detections_dir']} not found")
        else:
            # An empty glob column means "use evaluate_detections.py's
            # default", which is now the canonical resolver — both per-pass
            # naming conventions, not the batch-written shape alone (D6).
            glob = row["glob"]
            if glob:
                matches = list(det_dir_abs.glob(glob))
            else:
                matches = resolve_pool_passes(det_dir_abs, allow_multiple=True)
            if not matches:
                problems.append(
                    f"detections_dir+glob produced 0 matches: "
                    f"{row['detections_dir']} + {glob or '<resolver default>'}"
                )
    elif row["batch"]:
        if not (REPO_ROOT / row["batch"]).exists():
            problems.append(f"batch={row['batch']} not found")
    else:
        problems.append("no detection source set (detections / detections_dir / batch)")
    return problems


def classify_group(eval_path: Path) -> str:
    """Map an eval-path to a per-group commit bucket.

    Mirrors the §8 plan's commit-grouping logic, extended to cover the
    cells that are out-of-scope for the daylight-sweep plan but in-scope
    for the BCa migration.

    Args:
        eval_path: Absolute path to the cell's ``evaluation.json``.

    Returns:
        Group key string used in the per-group commit summary.
    """
    rel = eval_path.relative_to(REPO_ROOT)
    parts = rel.parts
    # ``results`` is parts[0]; the meaningful subtree is parts[1].
    if len(parts) < 2 or parts[0] != "results":
        return "other"
    top = parts[1]
    if top == "paper-eval":
        return "paper-eval"
    if top == "pairwise":
        return "pairwise-tile-size-30m"
    if top == "55maps-cleaned-gt-evaluation":
        return "55maps-cleaned-gt"
    if top.startswith("gold-standard"):
        return "gold-standard-extended-buffer-sweeps"
    if top.startswith(("h8-", "h10", "h12-")):
        return "h-series"
    if top == "phase3a-image-matrix" or top == "phase3a-text-matrix":
        return "phase3a-matrix"
    if top.startswith("verifier"):
        return "verifier-calibration"
    if top.endswith("-generalisation"):
        return "55maps-generalisation"
    return f"other:{top}"


def build_queue() -> tuple[list[dict[str, str]], dict[str, int]]:
    """Build the migration queue plus a skip-counter telemetry dict.

    Returns:
        Tuple ``(rows, skip_counter)`` where ``rows`` is the list of
        queue-CSV rows and ``skip_counter`` counts cells skipped by
        reason (``already_bca``, ``not_evaluate_detections``, etc.).
    """
    rows: list[dict[str, str]] = []
    skipped: Counter = Counter()
    for eval_path in enumerate_eval_cells():
        in_scope, reason = needs_migration(eval_path)
        if not in_scope:
            skipped[reason] += 1
            continue
        try:
            with open(eval_path) as f:
                d = json.load(f)
        except Exception as e:
            skipped[f"reload_failed:{e!s}"] += 1
            continue
        # ``recover_recipe`` is the D22 fallback chain: a cell with no
        # ``cli_args`` is still queueable if ``input_files`` names its
        # inputs. Only a cell with neither is genuinely unqueueable.
        recipe = recover_recipe(d)
        if not recipe:
            skipped["no_recipe(no cli_args, no input_files)"] += 1
            continue
        rows.append(make_row(eval_path, d))
    return rows, dict(skipped)


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"Canonical output CSV (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--no-runner-copy", action="store_true",
        help=(
            "Do not write a copy at /tmp/bootstrap-10k-jobs.csv. By default "
            "the runner expects that hard-coded path; the copy keeps the "
            "runner unchanged."
        ),
    )
    parser.add_argument(
        "--validate-paths", action="store_true",
        help="Verify every detection / bounds / GT path exists on disk before writing.",
    )
    args = parser.parse_args()

    print("Building BCa migration queue...")
    print()
    rows, skipped = build_queue()
    print(f"  Queue rows: {len(rows)}")
    print()
    if skipped:
        print("  Skipped:")
        for reason, n in sorted(skipped.items()):
            print(f"    {reason:62s} {n:4d}")
        print()

    # Per-group breakdown for the per-group commit later.
    by_group: Counter = Counter()
    for r in rows:
        eval_path = REPO_ROOT / r["eval_path"]
        by_group[classify_group(eval_path)] += 1
    print("  Per-group breakdown:")
    for g, n in sorted(by_group.items()):
        print(f"    {g:42s} {n:4d}")
    print()

    if args.validate_paths:
        print("Validating paths...")
        n_valid = 0
        all_errors: list[str] = []
        for i, r in enumerate(rows):
            errs = validate_row(r)
            if errs:
                all_errors.append(f"[row {i}] {r['eval_path']}: {'; '.join(errs)}")
            else:
                n_valid += 1
        print(f"  {n_valid}/{len(rows)} rows have all required paths on disk")
        if all_errors:
            print("Validation errors (first 50):", file=sys.stderr)
            for err in all_errors[:50]:
                print(f"  {err}", file=sys.stderr)
            print("Validation FAILED; not writing CSV.", file=sys.stderr)
            return 2
        print()

    # Write the canonical CSV plus runner-compatible copy.
    fieldnames = [
        "status", "eval_path", "output_dir",
        "detections", "detections_dir", "glob", "batch",
        "bounds", "ground_truth",
        "buffers", "bootstrap", "seed",
        "label", "mcc",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)

    targets: list[Path] = [args.output]
    if not args.no_runner_copy:
        targets.append(RUNNER_QUEUE)

    for target in targets:
        with open(target, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            for row in rows:
                w.writerow(row)
        print(f"Wrote {len(rows)} rows to {target}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
