#!/usr/bin/env python3
"""
Derive the r2 reference-revision instruction set from the PI's two audits.

`planning/reference-revision-2026-09-06.md` § 1: revision r2 of the 55-map
best-available ground truth is the Ruling-21 standardised reference plus an
audit instruction set — one row per change, derived deterministically from
the two adjudication files so the revision can be regenerated byte-for-byte
and every change traced to the mark that caused it.

Sources (both written by `scripts/empty_tile_adjudicate.py`):

- `results/cluster-audit/adjudication.json` (``--mode census``):
  removals from class ``gt-error-flag`` (the flagged reference point);
  additions from classes ``detected`` (a mound the model found that the
  reference lacks), ``true-double-miss``, and ``proposed-but-filtered``.
- `results/empty-tile-audit/adjudication.json` (``--mode empty``):
  additions from class ``true-double-miss``.

The PI's re-reviews are recorded as provenance, not applied as filters:
the census edge-safety final check (`results/cluster-audit/final-check/`)
confirmed all 13 known-in-GT marks, which change nothing; the empty-stratum
re-review (`results/empty-tile-audit/final-check/`) re-viewed the five
double-misses with the original mark overlaid and the PI reported "no
errors" (2026-09-06) — the app verdict saved was ``n`` on all five, which
in that pass meant "the mark stands" (the pass had no known points to
confirm against). That reading is written into the ``note`` column so a
reader can see it rather than infer it.

Output (``--out-dir``, default ``results/reference-revision-r2``):

- ``audit-revision-instructions.csv`` — columns: action (add|remove),
  audit (census|empty), class, gt_id (removals), x, y (EPSG:32635, the
  reviewer's mark), tile_name, position (1-based), symbol, note.
  Removals sorted by gt_id, then additions by (audit, position).
- ``audit-revision-summary.json`` — counts and the source file hashes.

Usage::

    python scripts/derive_audit_revision_instructions.py [--out-dir DIR]

Zero API, instant. Deterministic.

Created: 2026-09-06 (Session 148)
Author: Shawn Ross, Claude Code
Licence: Apache 2.0
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

SOURCES = {
    "census": PROJECT_ROOT / "results/cluster-audit/adjudication.json",
    "empty": PROJECT_ROOT / "results/empty-tile-audit/adjudication.json",
}
ADD_CLASSES = {
    "census": ("detected", "true-double-miss", "proposed-but-filtered"),
    "empty": ("true-double-miss",),
}
EMPTY_RECHECK_NOTE = ("re-reviewed 2026-09-06 on its own tile with the mark overlaid; PI: "
                      "'no errors' (app verdict n = the mark stands)")
COLUMNS = ["action", "audit", "class", "gt_id", "x", "y", "tile_name", "position",
           "symbol", "note"]


def sha256(path: Path) -> str:
    """Hex digest of a file, for the summary's provenance block."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    """Write the instruction CSV and its summary."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", default="results/reference-revision-r2")
    args = ap.parse_args()
    out = PROJECT_ROOT / args.out_dir
    out.mkdir(parents=True, exist_ok=True)

    adj = {k: json.loads(p.read_text()) for k, p in SOURCES.items()}
    for k, a in adj.items():
        if a.get("reference") != "standardised":
            raise RuntimeError(f"{k}: adjudication reference is {a.get('reference')!r}, "
                               "not the standardised reference r2 builds on")

    removals: dict[str, dict] = {}
    for r in adj["census"]["per_mark"]:
        if r["class"] != "gt-error-flag":
            continue
        gid = r.get("flagged_gt_id")
        if not gid or str(gid).startswith("not-in-reference"):
            logger.info("flag on %s names no reference point (%s) — nothing to remove",
                        r["tile_name"], gid)
            continue
        removals.setdefault(gid, {"tiles": [], "positions": []})
        removals[gid]["tiles"].append(r["tile_name"])
        removals[gid]["positions"].append(int(r["order_index"]) + 1)

    rows: list[dict] = []
    for gid in sorted(removals):
        d = removals[gid]
        rows.append({"action": "remove", "audit": "census", "class": "gt-error-flag",
                     "gt_id": gid, "x": "", "y": "", "tile_name": ";".join(d["tiles"]),
                     "position": ";".join(str(p) for p in d["positions"]),
                     "symbol": "Known (yellow) mound is NOT a mound — GT error",
                     "note": f"flagged from {len(d['tiles'])} tile(s); collapsed onto the "
                             "reference point at the 15 m floor"})

    additions: list[dict] = []
    for audit, classes in ADD_CLASSES.items():
        for r in adj[audit]["per_mark"]:
            if r["class"] not in classes:
                continue
            note = {
                "detected": "mound the model found (3.7 arm-2 within 5.1 m) that the "
                            "reference lacks",
                "true-double-miss": "neither students nor any model; nearest anything "
                                    f"{r['nearest_anything_m']} m",
                "proposed-but-filtered": "proposed by the 3.7 K=5 union (2 votes, 3.7-verifier "
                                         "p 0.98), killed by the k=5 vote gate",
            }[r["class"]]
            if audit == "empty":
                note += "; " + EMPTY_RECHECK_NOTE
            additions.append({"action": "add", "audit": audit, "class": r["class"], "gt_id": "",
                              "x": f"{r['x_world']:.2f}", "y": f"{r['y_world']:.2f}",
                              "tile_name": r["tile_name"], "position": int(r["order_index"]) + 1,
                              "symbol": r["symbol"], "note": note})
    additions.sort(key=lambda d: (d["audit"], int(d["position"])))
    rows.extend(additions)

    path = out / "audit-revision-instructions.csv"
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    summary = {
        "generated_from": {k: {"path": str(p.relative_to(PROJECT_ROOT)), "sha256": sha256(p),
                               "generated": adj[k]["generated"], "reference": adj[k]["reference"]}
                           for k, p in SOURCES.items()},
        "removals": len(removals),
        "additions": len(additions),
        "additions_by_audit_class": {f"{d['audit']}/{d['class']}": sum(
            1 for e in additions if (e["audit"], e["class"]) == (d["audit"], d["class"]))
            for d in additions},
        "instruction_rows": len(rows),
    }
    (out / "audit-revision-summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    logger.info("removals %d, additions %d -> %s", len(removals), len(additions),
                path.relative_to(PROJECT_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
