#!/usr/bin/env python3
"""
Render the r2 board's post-hoc addendum into its two published documents.

The 35-cell board in ``final_board_50m.json`` / ``final-board-50m.md`` is
**signed**: its greedy-clique tiers and its 595-pair Benjamini-Hochberg
family were computed over exactly those cells, and the PI has ruled twice
(2026-09-13, carried forward 2026-09-20) that cells added afterwards do NOT
re-tier it. ``scripts/final_board_build.py`` is the only thing that may write
the tiered board, and it is not run here.

So a post-hoc cell needs a home beside the tiered board rather than in it.
This script is that home. It reads every ``... (post-hoc)`` cell of
``cells_manifest.json`` whose basis this addendum covers, reads its committed
``evaluation.json``, and writes:

* ``final_board_50m.json`` -> a top-level ``addendum_cells`` list, replaced
  wholesale each run, carrying ``tier: null`` and ``group: null`` so no
  consumer can mistake an addendum row for a tiered one; and an
  ``addendum`` block recording what the list is and why it is separate.
* ``final-board-50m.md`` -> one delimited section, replaced in place,
  holding the prose and the table. The banner and the changelog are NOT
  touched: they are the human-written revision trail the project's
  document revision policy asks for.

Idempotent: re-running after a second set lands refreshes the same block
rather than appending a second one. Nothing outside the two documents is
written, and the tiered ``cells`` / ``tiers`` / ``pairwise`` blocks are
never read for writing.

Usage::

    python scripts/final_board_addendum_render.py [--reference r2]

Zero API, seconds of compute.

Created: 2026-09-20 (Session 157)
Author: Shawn Ross, Claude Code
Licence: Apache 2.0
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.build_55map_leaderboard import board_home  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

HEADLINE_M = 50
BEGIN = ("<!-- BEGIN board-addendum — generated by "
         "scripts/final_board_addendum_render.py; edit the script -->")
END = "<!-- END board-addendum -->"
ANCHOR = "## Provenance and gates"

#: Bases the addendum table covers. The tile-MCC optimum is NOT among them:
#: PI ruling 2026-09-21 dropped it from the boards under both definitions —
#: unconstrained and at-the-carried-k — and moved it to its own presentation,
#: results/tile-presence-2026-09-21/. Those cells stay on disk with their
#: committed evaluations and are re-labelled in cells_manifest.json; this
#: renderer simply no longer tables them, and the prose points at the table
#: that does.
COVERED = ("carried-analogue (post-hoc)",)

#: Where the tile-MCC optimum went. One line in the prose, so a reader of the
#: board never has to work out why the column disappeared.
TILE_PRESENCE_HOME = "results/tile-presence-2026-09-21/"

PROSE = """## Addendum: post-hoc cells beside the tiered board

The 35-cell table at the head of this document is the **signed** board:
its greedy-clique tiers and its 595-pair Benjamini–Hochberg (BH) family
were computed over exactly those cells. The cells below were
materialised and scored afterwards on the same instrument —
`scripts/evaluate_detections.py`, reference r2, the 8,541-tile
evaluation frame, 14 buffers, tile-level bias-corrected and accelerated
(BCa) bootstrap of 10,000 draws at seed 42, `--mcc` — but the board was
**not** re-tiered for them (PI ruling 2026-09-13, carried forward
2026-09-20). They therefore carry no tier and no group letter, and they
are **post-hoc** nominations, not registered claims. Read them as point
estimates with intervals beside the tiered rows; a difference between an
addendum row and a tiered row has not been through the board's pairwise
family.

`FOURTH-N5-oracle` sits off the tiered board for the same reason and is
not repeated here: it is a tiered-board-eligible oracle cell whose
scored evaluation is committed at
`cells/FOURTH-N5-oracle/evaluation.json` and whose condition is
registered, but the board was not rebuilt when it landed on 2026-09-13.

**Carried-analogue cells** (`carried-analogue (post-hoc)`) take their
family's top-rung GS-carried probability — ARM1 (0.10, k5), ARM2
(0.80, k5), FOURTH (0.98, k10) — and apply that same threshold downward
at a lower rung, with `k` set to the rung's own N. The canonical grid
board already published this construction for the two arms
(`results/gemini37-55map-2026-08-31/grid-board/grid_board.json`,
`basis: "carried-analogue"`); it was never carried onto the r2 board, so
until 2026-09-20 an image *carried* cell at K = 1 or K = 3 could only be
compared with a text *oracle*, which flatters the text track and
understates the image-minus-text gap at K = 1 by a factor of 2.4
(`reports/comparability-inventory-37-runs-2026-09-20.md` § 3.2).

**The tile-MCC optimum is not on this board.** It was briefly published
here as an "MCC oracle", first unconstrained (PI ruling 2026-09-20 item 2)
and then pinned to each family's carried vote count (ruling 6c, same day).
**PI ruling 2026-09-21 dropped it under both definitions.** Every one of the
board's 23 families puts its unconstrained tile-MCC optimum at the lowest
vote count its sweep offers, so beside an F1 oracle it reads as a rival
configuration when it is really a vote-threshold choice wearing a metric's
name. It is presented instead — with its vote count as a column and the
verifier pool it would need priced — in
[`results/tile-presence-2026-09-21/`](../tile-presence-2026-09-21/leaderboard.md).
Tile-MCC itself stays on this board, reported beside micro-F1 at the
carried and F1-oracle points, where both metrics describe the same
configuration. The cells remain on disk with their committed evaluations,
re-labelled in `cells_manifest.json`.
"""


HEADER = ("| cell | basis | point | F1@50 | 95% CI | P@50 | R@50 | "
          "tile-MCC | 95% CI | n |")
RULE = "|---|---|---|---:|---|---:|---:|---:|---|---:|"


def _rel(path: Path) -> str:
    """A repository-relative path for logging, or the absolute one.

    ``main`` runs against ``tmp_path`` under test, where ``relative_to``
    raises rather than logging, so the fallback is deliberate.
    """
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def headline(evaluation: Path) -> dict:
    """The 50 m row and tile-MCC of one committed cell evaluation.

    Args:
        evaluation: Path to the cell's ``evaluation.json``.

    Returns:
        ``{"n_detections", "f1_50", "ci", "precision_50", "recall_50",
        "mcc", "mcc_ci"}``.

    Raises:
        SystemExit: If the evaluation has no 50 m row (a cell scored with
            a different buffer ladder must not be tabled beside these).
    """
    summary = json.loads(evaluation.read_text())["summary"]
    rows = [b for b in summary["buffers"]
            if b["buffer_metres"] == HEADLINE_M]
    if not rows:
        raise SystemExit(f"{evaluation}: no {HEADLINE_M} m row")
    row = rows[0]
    mcc = summary["tile_classification"]["mcc"]
    return {
        "n_detections": int(summary["n_detections"]),
        "f1_50": row["f1"],
        "ci": [row["f1_ci_lower"], row["f1_ci_upper"]],
        "precision_50": row["precision"],
        "recall_50": row["recall"],
        "mcc": mcc["point"],
        "mcc_ci": [mcc["ci_lower"], mcc["ci_upper"]],
    }


def addendum_rows(out: Path, bases: tuple[str, ...] = COVERED) -> list[dict]:
    """Every covered post-hoc cell, scored, sorted by F1@50 descending.

    Args:
        out: The board home.
        bases: The manifest bases to take. Defaults to
            :data:`COVERED`; the parameter is kept so a caller can table a
            different set without a second reader.

    Returns:
        One dict per cell, in the tiered board's own cell schema plus
        ``tier``/``group`` pinned to ``None`` and the manifest ``note``.

    Raises:
        SystemExit: If a covered cell has no committed evaluation.
    """
    manifest = json.loads((out / "cells_manifest.json").read_text())["cells"]
    rows: list[dict] = []
    for cell in manifest:
        if cell.get("basis") not in bases:
            continue
        evaluation = out / "cells" / cell["label"] / "evaluation.json"
        if not evaluation.is_file():
            raise SystemExit(
                f"{cell['label']}: no evaluation.json — run "
                "scripts/r2_score_cells.py --stage board first")
        rows.append({"label": cell["label"], "basis": cell["basis"],
                     "point": cell["point"], **headline(evaluation),
                     "tier": None, "group": None, "cost_usd": None,
                     "note": cell.get("note")})
    rows.sort(key=lambda r: -r["f1_50"])
    logger.info("addendum: %d scored post-hoc cells", len(rows))
    return rows


def _short_basis(basis: str) -> str:
    """The basis as a table cell: no ``post-hoc`` noise, no date stamp."""
    return (basis.replace(" (post-hoc, 2026-09-20)", "")
            .replace(", unconstrained k (post-hoc, superseded 2026-09-20)",
                     " (unconstrained k)")
            .replace(" (post-hoc)", ""))


def render_table(rows: list[dict]) -> str:
    """The markdown table for the addendum section."""
    lines = [HEADER, RULE]
    for r in rows:
        lines.append(
            f"| {r['label']} | {_short_basis(r['basis'])} | "
            f"{r['point']} | {r['f1_50']:.4f} | "
            f"[{r['ci'][0]:.4f}, {r['ci'][1]:.4f}] | "
            f"{r['precision_50']:.4f} | {r['recall_50']:.4f} | "
            f"{r['mcc']:.4f} | "
            f"[{r['mcc_ci'][0]:.4f}, {r['mcc_ci'][1]:.4f}] | "
            f"{r['n_detections']} |")
    return "\n".join(lines)


def splice(markdown: str, block: str) -> str:
    """Replace the delimited addendum block, or insert it before the anchor.

    Args:
        markdown: The board document.
        block: The rendered block, delimiters included.

    Returns:
        The document with exactly one addendum block.

    Raises:
        SystemExit: If neither the delimiters nor the anchor heading is
            present, so the script cannot say where the block belongs.
    """
    if BEGIN in markdown and END in markdown:
        head, rest = markdown.split(BEGIN, 1)
        _old, tail = rest.split(END, 1)
        return head + block + tail
    if ANCHOR not in markdown:
        raise SystemExit(
            f"final-board-50m.md carries neither the addendum delimiters "
            f"nor the {ANCHOR!r} anchor — refusing to guess where the "
            "block belongs")
    head, tail = markdown.split(ANCHOR, 1)
    return head + block + "\n" + ANCHOR + tail


def main(reference: str = "r2") -> int:
    """Render the addendum into both published board documents.

    Args:
        reference: Board vintage (only ``r2`` carries these cells).

    Returns:
        Process exit code.
    """
    out = board_home(reference)
    rows = addendum_rows(out)

    board_path = out / "final_board_50m.json"
    board = json.loads(board_path.read_text())
    n_tiered = len(board["cells"])
    board["addendum_cells"] = rows
    # PI ruling 2026-09-21: the tile-MCC optimum is off this board under both
    # definitions, so the superseded block goes with it rather than lingering
    # as a stale list. The cells are on disk and in cells_manifest.json.
    board.pop("addendum_superseded_cells", None)
    board["addendum"] = {
        "what": "post-hoc cells scored on this board's instrument but NOT "
                "members of its tiered family",
        "tiered_cells": n_tiered,
        "why_untiered": "the board is signed; the PI ruled 2026-09-13, "
                        "carried forward 2026-09-20, that cells landing "
                        "after it do not re-tier it "
                        "(scripts/final_board_build.py was not re-run)",
        "bases": list(COVERED),
        "tile_mcc_optimum": "NOT on this board under either definition (PI "
                            "ruling 2026-09-21). Presented with its vote "
                            "count and its verifier pool cost in "
                            + TILE_PRESENCE_HOME + "; the cells remain on "
                            "disk, re-labelled in cells_manifest.json",
        "generated_by": "scripts/final_board_addendum_render.py",
    }
    board_path.write_text(json.dumps(board, indent=2) + "\n")
    logger.info("wrote %s (%d tiered cells, %d addendum cells)",
                _rel(board_path), n_tiered, len(rows))

    md_path = out / "final-board-50m.md"
    block = f"{BEGIN}\n{PROSE}\n{render_table(rows)}\n\n{END}"
    md_path.write_text(splice(md_path.read_text(), block))
    logger.info("wrote %s", _rel(md_path))
    return 0


if __name__ == "__main__":
    _ap = argparse.ArgumentParser(description=__doc__)
    _ap.add_argument("--reference", choices=["standardised", "r2"],
                     default="r2",
                     help="Board vintage to render into (default: r2).")
    _a = _ap.parse_args()
    sys.exit(main(_a.reference))
