#!/usr/bin/env python3
"""
Regenerate Per-Architecture Leaderboard Markdown Tables from JSON
==================================================================

Fixes Task #13 (the per-architecture leaderboard MD tier-table
overwrite bug). Stage 1 of the per-buffer F1 re-tiering work
(commits up to ``ccc320ea``) ran ``build_tiered_leaderboard.py``
once per (stratum, primary buffer, q-level), passing
``--buffers 20 30 40 50 100`` on every invocation. The MD writer
loops over *all* listed buffers each pass, so every later pass
overwrites the earlier passes' MD files with its own primary-buffer
tiering — but with each MD's own buffer-specific F1 column. Net
effect: per-stratum MD files at non-final-pass buffers display the
LAST pass's tier composition with the LOCAL buffer's F1 metrics.

The corresponding JSON files are correct (each pass writes only one
JSON, named for that pass's primary buffer). This script reads each
JSON, reconstructs ``SelectedCondition`` instances, and re-renders
the MD via the production ``write_leaderboard_markdown`` function so
formatting is byte-identical to a fresh build.

Scope:

- Walks the 7 populated per-architecture strata
  (era1/single-pass, era1/consensus, era2/single-pass,
  era2/consensus, era2/single-pass+PV, era2/pv, era3/consensus).
- For each stratum, regenerates every ``leaderboard_tiers*.md`` for
  which a sibling ``.json`` exists. This covers F1 q=0.05, F1 q=0.01,
  MCC q=0.05, and MCC q=0.01 at every buffer the JSON exists for.
  In practice the F1 JSONs exist at all 5 buffers (Session 79
  contributed the 20 m JSON; Stage 1 added 30/40/50/100 m JSONs);
  the MCC JSONs exist only at 20 m (one MCC pass per stratum).
- The ``leaderboard_all_evaluations.json`` file is left untouched —
  it has no MD sibling.

The MCC MDs at non-20 m buffers do not have a sibling JSON, but they
were also written by the buggy loop. Because MCC tier composition is
buffer-invariant in this codebase, the MCC MDs at all 5 buffers
share the same tier composition; the per-buffer F1 column rightly
varies. Those MDs are regenerated by reading the 20 m MCC JSON and
re-rendering at each buffer it appeared at.

Usage::

    python scripts/regenerate_per_arch_md_from_json.py
    python scripts/regenerate_per_arch_md_from_json.py --dry-run
    python scripts/regenerate_per_arch_md_from_json.py --verify

Author: Claude Code (Opus 4.7)
Created: 2026-04-26
Licence: Apache 2.0
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from build_tiered_leaderboard import (  # noqa: E402
    SelectedCondition,
    write_leaderboard_markdown,
)

# The 7 strata that have full per-buffer leaderboards. The remaining
# 5 directories under ``results/leaderboard/per-architecture/`` exist
# as placeholders only (1 file each — typically a README) and are
# excluded.
POPULATED_STRATA = [
    Path("era1") / "single-pass",
    Path("era1") / "consensus",
    Path("era2") / "single-pass",
    Path("era2") / "consensus",
    Path("era2") / "single-pass+PV",
    Path("era2") / "pv",
    Path("era3") / "consensus",
]

PER_ARCH_ROOT = (
    PROJECT_ROOT / "results" / "leaderboard" / "per-architecture"
)

# All buffers used in the per-arch builds. The MCC JSON is only
# written at 20 m (one MCC pass per stratum), but the buggy loop
# wrote MCC MDs at all 5 buffers; so when the MCC JSON exists, we
# re-render MD at every buffer in this list.
ALL_BUFFERS = [20, 30, 40, 50, 100]


def reconstruct_selected_conditions(
    tier_dict_list: list[dict],
) -> list[SelectedCondition]:
    """Rebuild ``SelectedCondition`` instances from a JSON tier list.

    JSON serialises ``evaluations`` keys as strings (because JSON
    object keys are strings); the renderer expects ``int`` keys, so
    we convert them back here. ``geojson_path`` is rebuilt as a
    ``Path``.

    Args:
        tier_dict_list: One element of ``leaderboard_tiers_*m.json``
            ``tiers[].conditions`` array.

    Returns:
        List of ``SelectedCondition`` ready for
        ``write_leaderboard_markdown``.
    """
    out: list[SelectedCondition] = []
    for c in tier_dict_list:
        evaluations_int_keys = {
            int(k): v for k, v in c.get("evaluations", {}).items()
        }
        out.append(
            SelectedCondition(
                label=c["label"],
                geojson_path=Path(c["geojson"]),
                best_threshold=int(c["best_threshold"]),
                era=int(c["era"]),
                track=str(c["track"]),
                category=str(c["category"]),
                k=int(c["k"]),
                evaluations=evaluations_int_keys,
                condition_id="",  # Not stored in JSON; not needed by MD writer.
                tile_mcc=float(c.get("tile_mcc", 0.0)),
            )
        )
    return out


# Filename pattern parses out the q-level infix ("" or "_q01") and
# the buffer in metres, matching the writer-side template:
#   leaderboard_tiers{metric_infix}{fdr_infix}_{buf_m}m.{md|json}
# where metric_infix is "" for F1 and "_mcc" for MCC, and fdr_infix
# is "" for q=0.05 and "_q01" for q=0.01.
_PATTERN_JSON = re.compile(
    r"^leaderboard_tiers"
    r"(?P<metric_infix>(?:_mcc)?)"
    r"(?P<fdr_infix>(?:_q\d{2})?)"
    r"_(?P<buf>\d+)m\.json$"
)


def discover_md_targets_for_stratum(
    stratum_dir: Path,
) -> list[tuple[Path, Path, int]]:
    """Find every (json_source, md_target, buffer_metres) to render.

    For each JSON file in the stratum:

    - F1 JSON at buffer B → render MD at buffer B (one target).
    - MCC JSON at buffer B → render MD at every buffer in
      ``ALL_BUFFERS`` (because the buggy loop wrote MCC MDs at all
      5 buffers from a single MCC pass; we restore the same set,
      but with correct content).

    Args:
        stratum_dir: The per-architecture stratum directory.

    Returns:
        List of (json_path, md_path, buffer_metres_to_render) tuples.
        ``buffer_metres_to_render`` may differ from the JSON's own
        buffer in the MCC case.
    """
    targets: list[tuple[Path, Path, int]] = []
    if not stratum_dir.is_dir():
        return targets

    for json_path in sorted(stratum_dir.glob("leaderboard_tiers*.json")):
        m = _PATTERN_JSON.match(json_path.name)
        if not m:
            # ``leaderboard_all_evaluations.json`` and other files
            # do not match the per-buffer pattern — skip silently.
            continue
        metric_infix = m.group("metric_infix")
        fdr_infix = m.group("fdr_infix")
        json_buf = int(m.group("buf"))

        # The MD filename mirrors the JSON filename with .md suffix
        # at each rendered buffer.
        if metric_infix == "_mcc":
            buffers_to_render = ALL_BUFFERS
        else:
            buffers_to_render = [json_buf]

        for buf_m in buffers_to_render:
            md_name = (
                f"leaderboard_tiers{metric_infix}{fdr_infix}_{buf_m}m.md"
            )
            md_path = stratum_dir / md_name
            targets.append((json_path, md_path, buf_m))

    return targets


def regenerate_one(
    json_path: Path,
    md_path: Path,
    buffer_metres: int,
) -> None:
    """Re-render a single MD file from its source JSON.

    Args:
        json_path: Source JSON containing tier composition.
        md_path: Destination MD file (overwritten).
        buffer_metres: Buffer at which to display per-buffer metrics
            in the MD's score and CI columns.
    """
    with json_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    metadata = dict(payload.get("metadata", {}))
    # The metric / fdr_q metadata fields drive the renderer's header
    # and column layout; they are already in the JSON metadata block.

    # Reconstruct tiers as a list[list[SelectedCondition]] in the
    # order tiers appear in the JSON (tier 1 first, etc.).
    tiers: list[list[SelectedCondition]] = []
    for tier_obj in payload.get("tiers", []):
        tiers.append(reconstruct_selected_conditions(tier_obj.get("conditions", [])))

    write_leaderboard_markdown(
        tiers=tiers,
        buffer_metres=buffer_metres,
        output_path=md_path,
        metadata=metadata,
    )


def verify_one(
    json_path: Path,
    md_path: Path,
) -> tuple[bool, str]:
    """Confirm the MD's tier-1 condition count matches the JSON.

    Args:
        json_path: Source JSON.
        md_path: Sibling MD (post-regeneration).

    Returns:
        ``(ok, message)`` where ``ok`` is True on match.
    """
    with json_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    json_t1 = payload.get("tiers", [{}])[0].get("conditions", []) or []
    json_n = len(json_t1)

    md_text = md_path.read_text(encoding="utf-8")
    # Slice from "## Tier 1 " up to "## Tier 2 " (the trailing
    # space disambiguates "Tier 1" from "Tier 10").
    in_block = False
    rows = 0
    for line in md_text.splitlines():
        if line.startswith("## Tier 1 "):
            in_block = True
            continue
        if in_block and line.startswith("## Tier 2 "):
            break
        if in_block and line.startswith("| ") and line[2:].split(" |")[0].strip().isdigit():
            rows += 1

    ok = rows == json_n
    msg = f"json_t1={json_n} md_t1={rows}"
    return ok, msg


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate per-arch leaderboard MDs from sibling JSON.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List the files that would be regenerated without writing.",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="After regeneration, spot-check tier-1 counts JSON vs MD.",
    )
    args = parser.parse_args()

    all_targets: list[tuple[Path, Path, int]] = []
    for stratum in POPULATED_STRATA:
        stratum_dir = PER_ARCH_ROOT / stratum
        targets = discover_md_targets_for_stratum(stratum_dir)
        all_targets.extend(targets)

    print(f"Discovered {len(all_targets)} MD targets across "
          f"{len(POPULATED_STRATA)} populated strata.")

    if args.dry_run:
        for json_path, md_path, buf in all_targets:
            print(f"  would render {md_path.relative_to(PROJECT_ROOT)} "
                  f"@ {buf}m  <-  {json_path.name}")
        return 0

    n_done = 0
    for json_path, md_path, buf in all_targets:
        regenerate_one(json_path, md_path, buf)
        n_done += 1

    print(f"Regenerated {n_done} MD files.")

    if args.verify:
        n_ok = 0
        n_fail = 0
        # Verification is meaningful only for files where buffer in
        # the MD matches the buffer in the JSON (i.e. F1 case;
        # MCC MDs at non-20 m buffers reuse the 20 m JSON's tier
        # composition by design).
        verified: set[tuple[Path, Path]] = set()
        for json_path, md_path, buf in all_targets:
            m = _PATTERN_JSON.match(json_path.name)
            if not m:
                continue
            json_buf = int(m.group("buf"))
            if json_buf != buf:
                # MCC at non-20 m — same JSON, different MD buffer;
                # tier-1 count still matches JSON's tier-1 count.
                pass
            key = (json_path, md_path)
            if key in verified:
                continue
            verified.add(key)
            ok, msg = verify_one(json_path, md_path)
            status = "OK" if ok else "MISMATCH"
            if ok:
                n_ok += 1
            else:
                n_fail += 1
                print(f"  {status} {md_path.relative_to(PROJECT_ROOT)}: {msg}")
        print(f"Verification: {n_ok} OK, {n_fail} mismatch "
              f"(of {n_ok + n_fail} pairs).")
        if n_fail:
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
