"""Push rendered AB+ entries to Zotero as child notes (tracked re-authoring).

The original 2026-07-17 consolidation push ran from ad-hoc, never-committed
code — only its outputs (the specimen note and import manifests) were
committed. This module re-authors that step as a tracked, re-runnable
component, discovered as a gap during the 2026-07-24 AB+ audit; the
2026-07-24 /audit pass then hardened every live path (per-item POST failure
detection, index.md exclusion, API-failure vs no-note distinction,
incremental manifests, anchor-guarded stamping).

Behaviour:

- For each rendered entry (``outputs/section2-grounding/ab-plus/tranche-*/
  <citekey>.md``), locate the matching Zotero item in the Paper-B group
  collection (normalised-title join against the paper's bib files, the same
  discipline as ``zotero.resolve_collection``), convert the markdown body to
  HTML via pandoc, prepend the provenance banner, and create a child note.
- Idempotent: an item already carrying an AB+ marker note is skipped. A
  failed children fetch is reported as its own status, never conflated with
  "no note exists" (conflating the two would mint duplicates on a transient
  API error).
- Dry-run by default; pass ``--live`` to write. The manifest is rewritten
  after every record, so a mid-run crash still leaves a complete account of
  what was attempted.
- ``--stamp-provenance MAP.jsonl`` retrofits a model-attribution line into
  EXISTING marker notes that lack one, consuming the per-citekey map derived
  from archived session transcripts (see
  ``planning/ab-plus-model-provenance-2026-07-24.md``).

Credentials: reads ``ZOTERO_API_KEY_PAPER_B`` from
``~/personal-assistant/.env`` (group-library write scope for groupID 5861859
only — see the personal-assistant Zotero reference). All writes go through
the Zotero Web API; the local SQLite is only ever read (immutable mode).

Known conservative defaults (acceptable at current scale, noted for later):
one POST per note where the API accepts 50-item batches, and no
``Retry-After`` backoff — a full corpus pass is ~186 sequential calls.

Usage (from the repo root)::

    .venv/bin/python scripts/ab_plus/push_notes.py --entries \
        'outputs/section2-grounding/ab-plus/tranche-8/*.md' \
        --model claude-opus-4-8 --workflow-run wf_xxx --live
"""

from __future__ import annotations

import argparse
import glob
import html as html_mod
import json
import re
import sqlite3
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import date, datetime
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ab_plus.config import COLLECTION_KEY, REPO_ROOT, ZOTERO_DB
from ab_plus.zotero import _norm_title, parse_bib_titles

API_BASE = "https://api.zotero.org"
DEFAULT_GROUP_ID = "5861859"  # 2025-MQ-LLM-DH-software-longevity
ENV_PATH = Path.home() / "personal-assistant" / ".env"
ENV_KEY_NAME = "ZOTERO_API_KEY_PAPER_B"

# The marker phrase identifying an AB+ note — must match the 2026-07-17
# specimen (planning/zotero-consolidation-specimen-note-farquhar-2026-07-17.html)
# and the 93 notes already in the library. Do not reword casually: the audit
# tooling recognises AB+ coverage by this exact string.
MARKER = "<strong>AB+ annotated bibliography entry</strong>"
BANNER = (
    f"<p>{MARKER} (LLM-generated, advisory — summary and positioning are "
    "Claude's synthesis; verbatim quotes were checked deterministically and "
    "an independent verifier's flags are reproduced below unedited).</p>"
)
STAMP_SENTINEL = "Generated by <code>"


def _load_api_key() -> str:
    """Read the group-write API key from the personal-assistant .env."""
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        if line.startswith(f"{ENV_KEY_NAME}="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise SystemExit(f"{ENV_KEY_NAME} not found in {ENV_PATH}")


def _api(
    key: str,
    method: str,
    path: str,
    body: dict | list | None = None,
    version: int | None = None,
) -> tuple[int, dict | list | None]:
    """Minimal Zotero Web API call (stdlib only, no pyzotero dependency).

    Returns ``(status, payload)``. Transport failures (DNS, timeout,
    connection reset) return status 0 so callers can distinguish "the API
    said no" from "the API was never reached" — and neither is ever treated
    as "the resource does not exist". No error path echoes the key.
    """
    headers = {"Zotero-API-Key": key, "Zotero-API-Version": "3"}
    data = None
    if body is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(body).encode("utf-8")
    if version is not None:
        headers["If-Unmodified-Since-Version"] = str(version)
    req = urllib.request.Request(
        f"{API_BASE}{path}", data=data, headers=headers, method=method
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = resp.read()
            try:
                return resp.status, (json.loads(payload) if payload else None)
            except json.JSONDecodeError:
                return resp.status, None
    except urllib.error.HTTPError as exc:
        return exc.code, None
    except (urllib.error.URLError, TimeoutError, OSError):
        return 0, None


def _create_status(status: int, body: dict | list | None) -> str:
    """Interpret a ``POST /items`` response.

    The Zotero write API returns HTTP 200 even when every item in the batch
    fails — per-item errors arrive in the body's ``failed`` map, so a bare
    status check would record phantom successes (audit Critical, 2026-07-24).
    """
    if status == 0:
        return "api-unreachable"
    if status != 200:
        return f"api-error-{status}"
    if not isinstance(body, dict):
        return "api-error-unparseable-body"
    failed = body.get("failed") or {}
    if failed:
        first = next(iter(failed.values()))
        code = first.get("code", "?") if isinstance(first, dict) else "?"
        return f"api-item-failed-{code}"
    created = (body.get("successful") or {}) or (body.get("success") or {})
    return "created" if created else "api-error-empty-success"


def _insert_stamp(note_html: str, stamp: str) -> str | None:
    """Insert a stamp paragraph after the banner's closing ``</p>``.

    Returns None when no safe anchor exists (marker absent, or no ``</p>``
    after it) — the caller records that rather than splicing blindly, which
    would corrupt the note (find() returning -1 previously produced an
    insert at offset 3; audit Medium, 2026-07-24).
    """
    marker_at = note_html.find(MARKER)
    if marker_at == -1:
        return None
    close_at = note_html.find("</p>", marker_at)
    if close_at == -1:
        return None
    insert_at = close_at + len("</p>")
    return note_html[:insert_at] + stamp + note_html[insert_at:]


def _md_to_html(md_text: str) -> str:
    """Convert entry markdown to HTML with pandoc (matches the 2026-07 notes)."""
    result = subprocess.run(
        ["pandoc", "-f", "markdown", "-t", "html"],
        input=md_text, capture_output=True, text=True, check=True, timeout=120,
    )
    return result.stdout


def _provenance_paragraph(
    entry_path: Path,
    model: str | None,
    run_date: str | None,
    workflow_run: str | None,
) -> str:
    """Build the Source/provenance paragraph for the note banner."""
    resolved = entry_path.resolve()
    try:
        shown = str(resolved.relative_to(REPO_ROOT))
    except ValueError:  # entry outside the repo — show absolute, don't crash
        shown = str(resolved)
    rev = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "describe", "--always", "--dirty"],
        capture_output=True, text=True, timeout=10,
    ).stdout.strip() or "unknown"
    esc = html_mod.escape
    bits = [f"Source: <code>{esc(shown)}</code> @ commit <code>{esc(rev)}</code>"]
    bits.append(f"imported to Zotero {date.today().isoformat()}")
    if model:
        gen = f"Generated by <code>{esc(model)}</code>"
        if run_date:
            gen += f", run {esc(run_date)}"
        if workflow_run:
            gen += f", workflow <code>{esc(workflow_run)}</code>"
        bits.append(gen)
    return "<p>" + " · ".join(bits) + ".</p>"


def _citekey_from_entry(entry_path: Path) -> str | None:
    """Read the case-correct citekey from a rendered entry's field table.

    Returns None for files without one (e.g. a tranche ``index.md`` swept up
    by a ``tranche-N/*.md`` glob) — the caller records and continues; raising
    here aborted live runs mid-tranche (audit Critical, 2026-07-24).
    """
    match = re.search(
        r"\| \*\*citekey\*\* \| `([^`]+)` \|", entry_path.read_text(encoding="utf-8")
    )
    return match.group(1) if match else None


def _collection_item_keys(collection_key: str) -> list[tuple[str, str]]:
    """Return ``(title, item_key)`` for every non-deleted item in a collection."""
    con = sqlite3.connect(f"file:{ZOTERO_DB}?immutable=1", uri=True)
    try:
        return con.execute(
            """
            SELECT idv.value AS title, it.key AS item_key
            FROM collections c
            JOIN collectionItems ci ON ci.collectionID = c.collectionID
            JOIN items it           ON it.itemID = ci.itemID
            JOIN itemData idat       ON idat.itemID = it.itemID
            JOIN fields f            ON f.fieldID = idat.fieldID AND f.fieldName = 'title'
            JOIN itemDataValues idv  ON idv.valueID = idat.valueID
            WHERE c.key = ?
              AND it.itemID NOT IN (SELECT itemID FROM deletedItems)
            """,
            (collection_key,),
        ).fetchall()
    finally:
        con.close()


def _default_bib_paths() -> list[Path]:
    """Every bib the paper loads — the citekey↔title join must span them all.

    The 2026-07-24 audit showed a single-bib join is a trap: ``assembly/
    main.tex`` loads two bib resources, and the §2 AB+ tranches resolve
    against a third. Missing one silently drops citekeys from the map.
    """
    candidates = [
        REPO_ROOT / "assembly" / "paper-b.bib",
        REPO_ROOT / "assembly" / "section2-grounding.bib",
        # Every per-tranche refs bib: tranches 2-7 shipped their own bib
        # files, and omitting them dropped 27/93 map rows from the
        # 2026-07-24 back-fill join (worked around with --bib that day;
        # this makes the default complete).
        *sorted((REPO_ROOT / "outputs" / "section2-grounding").glob(
            "section2-refs-*.bib")),
    ]
    return [p for p in candidates if p.is_file()]


def _resolve_item_keys(bib_paths: list[Path], collection_key: str) -> dict[str, str]:
    """Map citekeys to Zotero item keys via normalised-title join."""
    bib_titles: dict[str, str] = {}
    for bib_path in bib_paths:
        for citekey, title in parse_bib_titles(bib_path).items():
            bib_titles.setdefault(citekey, title)
    by_norm = { _norm_title(t): k for t, k in _collection_item_keys(collection_key) }
    out: dict[str, str] = {}
    for citekey, title in bib_titles.items():
        item_key = by_norm.get(_norm_title(title))
        if item_key:
            out[citekey] = item_key
    return out


def _existing_marker_notes(key: str, group: str, item_key: str) -> list[dict] | None:
    """Return this item's AB+ marker notes, or None when the fetch FAILED.

    The None/[] distinction is load-bearing: treating a failed fetch as "no
    notes" made a transient 429 mint duplicate notes (audit Critical,
    2026-07-24). Paginated — the API caps unqualified requests at 25.
    """
    notes: list[dict] = []
    start = 0
    while True:
        status, children = _api(
            key, "GET",
            f"/groups/{group}/items/{item_key}/children"
            f"?itemType=note&limit=100&start={start}",
        )
        if status != 200 or not isinstance(children, list):
            return None
        notes.extend(children)
        if len(children) < 100:
            break
        start += 100
    return [n for n in notes if MARKER in n.get("data", {}).get("note", "")]


def _write_manifest(path: str, mode: str, live: bool, records: list[dict]) -> None:
    """Rewrite the manifest — called after every record so a crash loses nothing."""
    Path(path).write_text(
        json.dumps({"mode": mode, "live": live, "date": datetime.now().isoformat(
            timespec="seconds"), "records": records}, indent=2),
        encoding="utf-8",
    )


def _push_entries(args: argparse.Namespace, key: str) -> int:
    """Create one AB+ child note per rendered entry (skip if already present)."""
    entries = sorted(Path(p) for p in glob.glob(args.entries, recursive=True))
    if not entries:
        raise SystemExit(f"No entry files match {args.entries!r}")
    item_keys = _resolve_item_keys(
        [Path(args.bib)] if args.bib else _default_bib_paths(), args.collection
    )
    records: list[dict] = []
    for path in entries:
        record: dict = {"entry": str(path)}
        records.append(record)
        try:
            citekey = _citekey_from_entry(path)
            record["citekey"] = citekey
            item_key = item_keys.get(citekey) if citekey else None
            record["item_key"] = item_key
            if not citekey:
                record["status"] = "no-citekey-row"
            elif not item_key:
                record["status"] = "no-item-match"
            else:
                existing = _existing_marker_notes(key, args.group, item_key)
                if existing is None:
                    record["status"] = "children-fetch-failed"
                elif existing:
                    record["status"] = "skipped-existing-note"
                elif not args.live:
                    record["status"] = "dry-run-would-create"
                else:
                    note_html = (
                        BANNER
                        + _provenance_paragraph(
                            path, args.model, args.run_date, args.workflow_run
                        )
                        + "<hr/>"
                        + _md_to_html(path.read_text(encoding="utf-8"))
                    )
                    status, body = _api(
                        key, "POST", f"/groups/{args.group}/items",
                        body=[{"itemType": "note", "parentItem": item_key,
                               "note": note_html, "tags": [], "collections": []}],
                    )
                    record["status"] = _create_status(status, body)
        except Exception as exc:  # record and continue; the manifest is the log
            record["status"] = f"error:{type(exc).__name__}"
            record["detail"] = str(exc)[:200]
        _write_manifest(args.manifest, "push", args.live, records)
        print(f"{record.get('citekey') or path.name:40s} {record['status']}")
    print(f"Manifest: {args.manifest}")
    return 0


def _stamp_provenance(args: argparse.Namespace, key: str) -> int:
    """Retrofit a model-attribution line into existing AB+ notes lacking one."""
    rows = [
        json.loads(line)
        for line in Path(args.stamp_provenance).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    item_keys = _resolve_item_keys(
        [Path(args.bib)] if args.bib else _default_bib_paths(), args.collection
    )
    records: list[dict] = []
    for row in rows:
        citekey, model = row.get("citekey"), row.get("model")
        record = {"citekey": citekey, "model": model}
        records.append(record)
        try:
            if not citekey or not model:
                record["status"] = "malformed-map-row"
                continue
            item_key = item_keys.get(citekey)
            record["item_key"] = item_key
            if not item_key:
                record["status"] = "no-item-match"
                continue
            notes = _existing_marker_notes(key, args.group, item_key)
            if notes is None:
                record["status"] = "children-fetch-failed"
                continue
            unstamped = [
                n for n in notes if STAMP_SENTINEL not in n["data"]["note"]
            ]
            if not notes:
                record["status"] = "no-marker-note"
            elif not unstamped:
                record["status"] = "already-stamped"
            elif not args.live:
                record["status"] = "dry-run-would-stamp"
            else:
                note = unstamped[0]
                stamp = (
                    f"<p>Generated by <code>{html_mod.escape(model)}</code> "
                    "(attribution recovered from archived session transcripts, "
                    "2026-07-24 forensics — see "
                    "planning/ab-plus-model-provenance-2026-07-24.md).</p>"
                )
                stamped = _insert_stamp(note["data"]["note"], stamp)
                if stamped is None:
                    record["status"] = "no-stamp-anchor"
                else:
                    status, _ = _api(
                        key, "PATCH",
                        f"/groups/{args.group}/items/{note['data']['key']}",
                        body={"note": stamped},
                        version=note["data"]["version"],
                    )
                    record["status"] = (
                        "stamped" if status == 204 else
                        "api-unreachable" if status == 0 else f"api-error-{status}"
                    )
        except Exception as exc:
            record["status"] = f"error:{type(exc).__name__}"
            record["detail"] = str(exc)[:200]
        finally:
            _write_manifest(args.manifest, "stamp-provenance", args.live, records)
            print(f"{citekey or '<no citekey>':40s} {record['status']}")
    print(f"Manifest: {args.manifest}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Construct the argument parser."""
    parser = argparse.ArgumentParser(prog="ab_plus.push_notes", description=__doc__)
    parser.add_argument("--entries", help="glob of rendered entry .md files to push")
    parser.add_argument(
        "--stamp-provenance",
        help="JSONL map ({citekey, model} per line) — retrofit stamps instead of pushing",
    )
    parser.add_argument("--group", default=DEFAULT_GROUP_ID, help="Zotero group ID")
    parser.add_argument(
        "--collection", default=COLLECTION_KEY, help="collection key (default: config)"
    )
    parser.add_argument("--bib", help="BibTeX file for the citekey↔title join")
    parser.add_argument("--model", help="model ID pinned for the generation run")
    parser.add_argument("--run-date", dest="run_date", help="generation run date")
    parser.add_argument(
        "--workflow-run", dest="workflow_run", help="workflow run ID (wf_...)"
    )
    parser.add_argument(
        "--manifest",
        default=str(REPO_ROOT / "outputs" / "section2-grounding" / "ab-plus"
                    / ("zotero-push-manifest-"
                       f"{datetime.now().strftime('%Y-%m-%d-%H%M%S')}.json")),
        help="manifest output path (timestamped so same-day re-runs never overwrite)",
    )
    parser.add_argument(
        "--live", action="store_true", help="actually write (default: dry-run)"
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    args = build_parser().parse_args(argv)
    if bool(args.entries) == bool(args.stamp_provenance):
        raise SystemExit("Pass exactly one of --entries or --stamp-provenance.")
    key = _load_api_key()
    if args.stamp_provenance:
        return _stamp_provenance(args, key)
    return _push_entries(args, key)


if __name__ == "__main__":
    raise SystemExit(main())
